version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy-db
    command: ["postgres", "-c", "wal_level=logical"]
    networks:
      - pharmacy_network
    volumes:
      - postgres_data:/var/lib/postgresql

  redocly:
    image: redocly/cli:latest
    container_name: redocly_docs
    hostname: redocly_docs
    command:
      [
        "build-docs",
        "/spec/pharmacy.yaml",
        "--output",
        "/spec/build/index.html",
      ]
    volumes:
      - ../openAPI:/spec
    networks:
      - pharmacy_network

  redocly-server:
    image: nginx:alpine
    container_name: redocly_server
    hostname: redocly_server
    depends_on:
      - redocly
    ports:
      - "8081:80"
    volumes:
      - ../openAPI/build:/usr/share/nginx/html:ro
    networks:
      - pharmacy_network

networks:
  pharmacy_network:
    driver: bridge

volumes:
  postgres_data:
